# Compiles Cemu's community graphic packs into the core. The packs live in the
# dependencies/cemu_graphic_packs submodule; they are merged the way that
# repository's own release zip is made (Enhancements, Resolutions, Mods,
# Workarounds and src side by side), zipped, and written out as a byte array.
# LibretroGraphicPacks.cpp unpacks it into system/Cemu/graphicPacks. The core
# may not download anything by itself, and a separate download is one users
# make once and never update, so the packs ship with every build instead.
function(libretro_embed_graphic_packs out_file)
    set(packs_dir "${CMAKE_SOURCE_DIR}/dependencies/cemu_graphic_packs")
    set(stage_dir "${CMAKE_CURRENT_BINARY_DIR}/graphic_packs_stage")
    set(zip_file "${CMAKE_CURRENT_BINARY_DIR}/graphicPacks.zip")

    set(data "")
    set(size 0)
    set(hash "")
    if(EXISTS "${packs_dir}/Resolutions")
        file(REMOVE_RECURSE "${stage_dir}")
        file(MAKE_DIRECTORY "${stage_dir}")
        foreach(group Enhancements Resolutions Mods Workarounds src)
            file(GLOB children LIST_DIRECTORIES true "${packs_dir}/${group}/*")
            if(children)
                file(COPY ${children} DESTINATION "${stage_dir}")
            endif()
        endforeach()
        file(COPY "${packs_dir}/LICENSE.md" DESTINATION "${stage_dir}")
        file(REMOVE "${zip_file}")
        execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${zip_file}" --format=zip .
            WORKING_DIRECTORY "${stage_dir}" RESULT_VARIABLE tar_result)
        file(REMOVE_RECURSE "${stage_dir}")
        if(tar_result EQUAL 0 AND EXISTS "${zip_file}")
            file(SHA1 "${zip_file}" hash)
            file(READ "${zip_file}" hex HEX)
            string(LENGTH "${hex}" hex_len)
            math(EXPR size "${hex_len} / 2")
            string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," data "${hex}")
            message(STATUS "libretro: graphic packs compiled in (${size} bytes)")
        else()
            message(WARNING "libretro: could not zip the graphic packs, the core ships without them")
        endif()
    else()
        message(WARNING "libretro: dependencies/cemu_graphic_packs is missing (git submodule update --init), the core ships without graphic packs")
    endif()

    if(size EQUAL 0)
        set(data "0")
    endif()
    file(WRITE "${out_file}.tmp"
        "// Generated by embed_graphic_packs.cmake from dependencies/cemu_graphic_packs\n"
        "#include <cstddef>\n\n"
        "extern const unsigned char g_libretro_graphic_packs_zip[] = {${data}};\n"
        "extern const std::size_t g_libretro_graphic_packs_zip_size = ${size};\n"
        "extern const char g_libretro_graphic_packs_version[] = \"${hash}\";\n")
    file(COPY_FILE "${out_file}.tmp" "${out_file}" ONLY_IF_DIFFERENT)
endfunction()
